---
apiVersion: v1
data:
  username: a2FnZW50Cg==
  password: c2VjcmV0LXBhc3N3b3JkCg==
kind: Secret
metadata:
  name: kagent-db-app-password
  namespace: kagent
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "kagent-db"
  namespace: kagent
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: nfs-csi
  managed:
    roles:
      - name: kagent
        ensure: present
        login: true
        superuser: false
        inRoles:
          - postgres
        passwordSecret:
          name: kagent-db-app-password
  bootstrap:
    initdb:
      database: kagent-database
      owner: kagent
