---
apiVersion: v1
data:
  username: aGFyYm9yCg==
  password: c2VjcmV0LXBhc3N3b3JkCg==
kind: Secret
metadata:
  name: harbor-db-app-password
  namespace: harbor
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "harbor-db"
  namespace: harbor
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: nfs-csi
  managed:
    roles:
      - name: harbor
        ensure: present
        login: true
        superuser: false
        inRoles:
          - postgres
        passwordSecret:
          name: harbor-db-app-password
  bootstrap:
    initdb:
      database: harbor-database
      owner: harbor
